function getRandomNumber(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const initialData = [
  {
    name: "Alice",
    age: 30,
    occupation: "Engineer",
    city: "New York",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Bob",
    age: 25,
    occupation: "Designer",
    city: "San Francisco",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Charlie",
    age: 35,
    occupation: "Teacher",
    city: "Chicago",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Diana",
    age: 28,
    occupation: "Developer",
    city: "Seattle",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Eve",
    age: 32,
    occupation: "Manager",
    city: "Boston",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Frank",
    age: 29,
    occupation: "Analyst",
    city: "Denver",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Grace",
    age: 31,
    occupation: "Consultant",
    city: "Los Angeles",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Hank",
    age: 26,
    occupation: "Developer",
    city: "Austin",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Ivy",
    age: 34,
    occupation: "Engineer",
    city: "San Diego",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Jack",
    age: 27,
    occupation: "Designer",
    city: "Portland",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Karen",
    age: 36,
    occupation: "Teacher",
    city: "Miami",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Leo",
    age: 33,
    occupation: "Manager",
    city: "Atlanta",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Mona",
    age: 24,
    occupation: "Analyst",
    city: "Phoenix",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Nina",
    age: 29,
    occupation: "Consultant",
    city: "Dallas",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Oscar",
    age: 38,
    occupation: "Engineer",
    city: "Houston",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Paula",
    age: 27,
    occupation: "Designer",
    city: "Philadelphia",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Quinn",
    age: 30,
    occupation: "Developer",
    city: "Las Vegas",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Rob",
    age: 32,
    occupation: "Manager",
    city: "New Orleans",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Sara",
    age: 28,
    occupation: "Analyst",
    city: "Orlando",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
  {
    name: "Tom",
    age: 35,
    occupation: "Consultant",
    city: "San Antonio",
    "salary $/h": getRandomNumber(20, 150),
    experience: getRandomNumber(1, 10),
    performance: getRandomNumber(1, 100),
  },
];
